flowchart LR
    subgraph BC1["🏘️ Comunidad (Community)"]
        C1[Conjunto, Etapa, Casa, Propietario, Tenencia]
    end
    subgraph BC2["🔐 Identidad y Acceso (IAM)"]
        C2[Usuario, Rol, AsignacionEtapa, Credencial]
    end
    subgraph BC3["💰 Cartera (Ledger)"]
        C3[CuentaDeCartera, Cuota, Pago, Tarifa, MontoPagoPredefinido]
    end
    subgraph BC4["📣 Notificaciones (Notifications)"]
        C4[Notificacion, PlantillaCorreo, ColaEnvio]
    end

    BC3 -->|PropietarioId, EtapaId| BC1
    BC3 -->|CobradorId| BC2
    BC4 -->|PropietarioId, email| BC1
    BC2 -->|valida permisos| BC1
    BC2 -->|valida permisos| BC3
